project_id = "qkwctrccuqkjygqurqxt"

[functions.twitch-auth-exchange]
verify_jwt = false

[functions.twitch-auth-me]
verify_jwt = false

[functions.twitch-auth-logout]
verify_jwt = false

[functions.loyalty-balance]
verify_jwt = false

[functions.twitch-auth-exchange]
verify_jwt = false

[functions.twitch-auth-me]
verify_jwt = false

[functions.twitch-auth-logout]
verify_jwt = false

[functions.twitch-config]
verify_jwt = false