project_id = "qkwctrccuqkjygqurqxt"

[functions.twitch-auth-exchange]
verify_jwt = false

[functions.twitch-auth-me]
verify_jwt = false

[functions.twitch-auth-logout]
verify_jwt = false

[functions.loyalty-balance]
verify_jwt = false

[functions.twitch-config]
verify_jwt = false

[functions.claim-daily-reward]
verify_jwt = false

[functions.manage-streamelements-points]
verify_jwt = false

[functions.save-twitch-character]
verify_jwt = false

[functions.get-daily-login-status]
verify_jwt = false
